### ISSUE TITLE
Monitorian crashes when started on Windows 10 20H2

### ISSUE THREAD

**Issue by armak** [emoacht/Monitorian#141]
I updated to the 20H2 version, and Monitorian (lasted updated version from Microsoft Store) fails to start now after the update. It creates a misaligned pop up window in the lower right (only a sliver of the top is visible for a second or two), and then closes from two exceptions. The stack trace in the log files is listed below. I'm using two Dell U2713H monitors with DCC enabled.

```
[Date: 21/02/2021 18.47.26 Ver: 2.13.1.0]
System.Runtime.InteropServices.COMException: Creating an instance of the COM component with CLSID {77A1C827-FCD2-4689-8915-9D613CC5FA3E} from the IClassFactory failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)). HResult: -2147221164 ErrorCode: -2147221164
   at Monitorian.Core.Models.Monitor.LightSensor.SensorExists(Guid sensorTypeGuid)
   at Monitorian.Core.Models.Monitor.LightSensor.<>c.<.cctor>b__13_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Monitorian.Core.Models.Monitor.PowerManagement.get_CanAdaptiveBrightnessEnabled()
   at Monitorian.Core.Models.Monitor.PowerManagement.GetOnPowerSettingChanged()
   at Monitorian.Core.AppControllerCore.<InitiateAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Monitorian.AppController.<InitiateAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Monitorian.App.<OnStartup>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[Date: 21/02/2021 18.48.21 Ver: 2.13.1.0]
System.Runtime.InteropServices.COMException: Creating an instance of the COM component with CLSID {77A1C827-FCD2-4689-8915-9D613CC5FA3E} from the IClassFactory failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)). HResult: -2147221164 ErrorCode: -2147221164
   at Monitorian.Core.Models.Monitor.LightSensor.SensorExists(Guid sensorTypeGuid)
   at Monitorian.Core.Models.Monitor.LightSensor.<>c.<.cctor>b__13_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Monitorian.Core.Models.Monitor.PowerManagement.get_CanAdaptiveBrightnessEnabled()
   at Monitorian.Core.Models.Monitor.PowerManagement.GetOnPowerSettingChanged()
   at Monitorian.Core.AppControllerCore.<InitiateAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Monitorian.AppController.<InitiateAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Monitorian.App.<OnStartup>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Monitorian.App.Main()


```

**Comment by armak** [comment]
Apparently after it generates two of these dialogs, the app is still actually usable and seems fully functional, but will close after interacting with the dialog.
![image](https://user-images.githubusercontent.com/4991927/108632193-4fe06100-7476-11eb-8f3d-6574e86d2ff9.png)

**Comment by emoacht** [comment]
Thank you for the report.
The function in question is to check if ambient light sensor exists. I cannot reproduce this issue on my systems regardless of the existence of the sensor. But I understand this exception may be thrown.
Does your system has an ambient light sensor?

**Comment by armak** [comment]
No I don't think so. This is a desktop PC with two identical external monitors. Previously I had no issues with the application in Windows 10 version 1903.

**Comment by emoacht** [comment]
Okay, it is just for clarification.

**Comment by emoacht** [comment]
This issue is completely different from #296.
