### ISSUE TITLE
Mouse wheel over notification area icon

### ISSUE THREAD

**Issue by emoacht** [emoacht/Monitorian#637]
Regarding  the request to change the brightness by mouse wheel over the notification area icon, as I explained in #174, the implementation by global hook is very inefficient and thus not desirable.

Instead, I added a function to capture mouse wheel over the notification area icon by another approach in 4d7d95604f4eb7a789412c00097be490cc3b4357
In this implementation, when the mouse cursor enters the rectangle of notification area icon, a semi-transparent window will overlay the icon and receive mouse events. The management of that window is a little tricky and I need to test it for a while.

You can test this function by `/iconwheel` command-line option.

**Comment by duncansmart** [comment]
Great idea with the overlay window. However, the scrolling only affects one window when the sliders window is not showing, even though the unison checkboxes are selected for both monitors. The scrolling _does_ work as expected if the sliders window is first displayed and then the mouse is scrolled over the NotifyIcon.

**Comment by duncansmart** [comment]
Also, I set the Window background to `Argb(100, 255, 0, 0)` and inflated iconRect (`iconRect.Inflate(0, 20)`) so i can see the behaviour:

<img width="153" alt="image" src="https://github.com/user-attachments/assets/f45f8b3b-6ab3-4710-b1ec-59f607efe66f">

You can occasionally see the MouseLeave logic is unreliable: here my mouse has moved off to the right and the window is still visible:
<img width="166" alt="image" src="https://github.com/user-attachments/assets/db73d96f-e2ca-4806-affd-29d112939e45">

... OK fine but that also means that the task bar window (which is likely topmost too) can sometimes position itself _over_ our window e.g. if I click the taskbar to the left-hand side of the notification area, the task bar goes back on top, which blocks the mouse input - our window is unaware it's no longer on top so doesn't try to activate/reposition itself:
<img width="195" alt="image" src="https://github.com/user-attachments/assets/89a5e4f5-fbb1-4949-b677-b922f0a3166a">

Here you can see the overlay window has gone behind the task bar, hence the mouse messages from the cursor won't reach it:
<img width="203" alt="image" src="https://github.com/user-attachments/assets/559e6233-a3d2-473c-affe-45367ddde4fe">

**Comment by emoacht** [comment]
Thank you for the feedback.
Probably fixed by 712c1aad98255b941b544e8ac53919c48efdeb5e and e531e4730650c79d0795295a671f3d11c97cf528

**Comment by duncansmart** [comment]
- ✅ The icon mouse wheel option is very stable now
- 🤔 No improvement on the unison option.

**Comment by emoacht** [comment]
@VVispy To try this function use `/iconwheel` option. That's it.

**Comment by emoacht** [comment]
For the record, I got an InvalidOperationException.

```
System.InvalidOperationException: Cannot set Visibility or call Show, ShowDialog, or WindowInteropHelper.EnsureHandle after a Window has closed
   at System.Windows.Window.VerifyCanShow()
   at System.Windows.Window.CoerceVisibility(DependencyObject d, Object value)
   at System.Windows.DependencyObject.ProcessCoerceValue(DependencyProperty dp, PropertyMetadata metadata, EntryIndex& entryIndex, Int32& targetIndex, EffectiveValueEntry& newEntry, EffectiveValueEntry& oldEntry, Object& oldValue, Object baseValue, Object controlValue, CoerceValueCallback coerceValueCallback, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, Boolean skipBaseValueChecks)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at ScreenFrame.NotifyIconContainer.ShowOverlayWindow()
   at ScreenFrame.NotifyIconContainer.OnMouseMove(Object sender, MouseEventArgs e)
   at System.Windows.Forms.NotifyIcon.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.NotifyIcon.WmMouseMove(Message& m)
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by VVispy** [comment]
feature request: show the % or amount when scrolling like you can with the volume on win 11

<img width="126" height="77" alt="Image" src="https://github.com/user-attachments/assets/c617cc04-3bf8-4b09-b832-c13d103babae" />

**Comment by emoacht** [comment]
On the latest Windows 11, when Right-To-Left layout is applied and the notification icon locates in the taskbar (not in the overflow area), Shell_NotifyIconGetRect function returns incorrect location. As a result, icon scroll function will not work in this case. 
There is no workaround for this.

**Comment by kshitij-garg** [comment]
Hi everyone! 👋 Just wanted to drop a quick note that if you're looking for an immediate fix/implementation for this feature, I've compiled a suite of these quality-of-life updates into an unofficial fork called [Monitorian 2.0 Unofficial](https://github.com/kshitij-garg/Monitorian-2.0).

You can easily download the ready-to-run .exe from the [Latest Release Page](https://github.com/kshitij-garg/Monitorian-2.0/releases/tag/v2.0.0).

I've submitted this feature as a PR upstream, but in the meantime, feel free to use the unofficial build if you need it today. Huge thanks to @emoacht for the amazing original software!
