### ISSUE TITLE
'ToolTip' cannot have a logical or visual parent

### ISSUE THREAD

**Issue by emoacht** [emoacht/Monitorian#7]
I have occasionally experienced this exception when some hardware changes happen. No clue.
```
System.InvalidOperationException: 'ToolTip' cannot have a logical or visual parent.
   at System.Windows.Controls.ToolTip.OnAncestorChanged()
   at System.Windows.FrameworkElement.OnAncestorChangedInternal(TreeChangeInfo parentTreeState)
   at System.Windows.TreeWalkHelper.OnAncestorChanged(DependencyObject d, TreeChangeInfo info, Boolean visitedViaVisualTree)
   at System.Windows.DescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   at MS.Internal.PrePostDescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   at System.Windows.DescendentsWalker`1.VisitNode(FrameworkElement fe, Boolean visitedViaVisualTree)
   at System.Windows.DescendentsWalker`1.VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   at System.Windows.DescendentsWalker`1.WalkLogicalChildren(FrameworkElement feParent, FrameworkContentElement fceParent, IEnumerator logicalChildren)
   at System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren(FrameworkElement feParent, Boolean hasLogicalChildren)
   at System.Windows.DescendentsWalker`1.IterateChildren(DependencyObject d)
   at System.Windows.DescendentsWalker`1.StartWalk(DependencyObject startNode, Boolean skipStartNode)
   at MS.Internal.PrePostDescendentsWalker`1.StartWalk(DependencyObject startNode, Boolean skipStartNode)
   at System.Windows.TreeWalkHelper.InvalidateOnTreeChange(FrameworkElement fe, FrameworkContentElement fce, DependencyObject parent, Boolean isAddOperation)
   at System.Windows.Controls.Primitives.Popup.UpdatePlacementTargetRegistration(UIElement oldValue, UIElement newValue)
   at System.Windows.Controls.Primitives.Popup.DestroyWindow()
   at System.Windows.Controls.Primitives.Popup.<HideWindow>b__122_0(Object sender, EventArgs args)
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by danperor** [comment]
some times i have got this error  in my view Designer in vs2015
i use a button tooltip  custom style in this case.
and i fix it when i put my tooltip style  in the Resource dictionary
it resolved。
you can try this .

**Comment by emoacht** [comment]
@danperor Thank for your suggestion.
However, this error have been thrown even before I defined the style in this app. The location of the style does matter? How wired.

**Comment by emoacht** [comment]
I have not encountered this exception for long period and so decided to close this issue.
